name: arcgis_maps_toolkit_example
description: A series of example apps that demonstrate how to use the ArcGIS Maps SDK for Flutter Toolkit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  arcgis_maps: ^300.0.0
  arcgis_maps_toolkit:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  patrol: ^4.0.1

flutter:
  uses-material-design: true

patrol:
  app_name: arcgis_maps_toolkit_example
  android:
    package_name: com.esri.arcgis_maps_toolkit_example
  ios:
    bundle_id: com.esri.arcgisMapsToolkitExample
