name: arcgis_maps_toolkit_example
description: A series of example apps that demonstrate how to use the ArcGIS Maps SDK for Flutter Toolkit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  arcgis_maps: ^300.0.0
  arcgis_maps_toolkit:
    path: ../
  flutter:
    sdk: flutter
  go_router: ^16.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
