name: arcgis_maps_toolkit_example
description: A series of example apps that demonstrate how to use the ArcGIS Maps SDK for Flutter Toolkit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  arcgis_maps:
    path: ../../flutter/arcgis_maps
  arcgis_maps_toolkit:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
